# Generated by Django 3.0.5 on 2020-08-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
